spring:
  application:
    name: service-order
  zipkin:
    base-url: http://zipkin-service:9411
  sleuth:
    sampler:
      probability: 1.0
# sleuth.sampler.probability 是监控的百分比，默认的是0.1表示10%,这里给1.0表示全部监控
# spring.zipkin.base-url：是zipkin-server的服务路径
#  security:
#    user:
#      name: "client"
#      password: "client"

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file: var/log/service-order.log
server:
  port: 8764
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
#    prefer-ip-address: true
    hostname: service-order
#    metadata-map:
#      user.name:  ${spring.security.user.name}
#      user.password:  ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

